<?
	$categoryName="rooms";
	$categoryNum="02";
	$folderName="room";
	$topArea="topArea";
	$pageNum="200";
	$subNum="00";
	$pageTitle01="Room Preview";
	$pageTitle02="미리보기";
	$imgNum01="1";
?>
<? include_once ("./include/subTop.php"); ?>
<div id="wrap" class="sub <?=$folderName?> <?=$folderName?><?=$subNum?>">
	<? include_once ("./include/header.php"); ?>
	<div class="subArea">
		<? include_once ("./include/topArea.php"); ?>
		<div id="contents">
			<div class="subCon subCon01">
				<? include_once ("./include/subNav.php"); ?>
			</div>
			<div class="subCon subCon01">

				<!-- <div class="roomPre_01">
					<p>
					시원한 바람과 햇살이 들어오는 깔끔하고 편안한 공간,<br>
                    하늘캠핑장의 객실을 미리만나보세요.
					</p>
					<a href="#roomPre01" class="btn_scroll">객실배치도 확인하기</a>
				</div> -->
				<!-- <p class="roomPre_app">배치도를 좌우<i class="material-icons"></i>로 이동하세요.</p> -->
				<script src="/html/js/jquery.rwdImageMaps.min.js"></script>
				<script>
					$(document).ready(function(e) {
					$('img[usemap]').rwdImageMaps();
					});
				</script>
				<div class="roomPre_warp">
					<!-- Image Map Generated by http://www.image-map.net/ -->
					<img src="./images/room/map.jpg" usemap="#image-map" style="max-width:100%; margin: 0 auto;">
					<map name="image-map">
						<area target="" alt="auto" title="auto" href="/html/room.php?roomnum=03" coords="198,81,257,139" shape="rect">
						<area target="" alt="f - 1~5" title="f - 1~5" href="/html/room.php?roomnum=02" coords="271,81,589,139" shape="rect">
						<area target="" alt="c - 1~5" title="c - 1~5" href="/html/room.php?roomnum=01" coords="596,80,910,139" shape="rect">
						<area target="" alt="auto" title="auto" href="/html/room.php?roomnum=03" coords="173,209,231,398" shape="rect">
						<area target="" alt="auto" title="auto" href="/html/room.php?roomnum=03" coords="634,199,891,259" shape="rect">
						<area target="" alt="auto" title="auto" href="/html/room.php?roomnum=03" coords="325,451,461,511" shape="rect">
						<area target="" alt="auto" title="auto" href="/html/room.php?roomnum=03" coords="460,439,506,411,535,454,490,483" shape="poly">
						<area target="" alt="매점" title="매점" href="/html/special.php?cate=01" coords="113,412,74,463,164,536,201,478" shape="poly">
						<area target="" alt="야외수영장" title="야외수영장" href="/html/special.php?cate=03" coords="324,220,460,345" shape="rect">
						<area target="" alt="트램펄린" title="트램펄린" href="/html/special.php?cate=04" coords="468,253,530,316" shape="rect">
					</map>
				</div>
				<div class="common_typo">welcome to pension</div>
				<? include_once ("./include/roomList.php"); ?>
			</div>
		</div>
	</div>
<? include_once ("./include/footer.php"); ?>
